"""Generates generated_client.py — the setup step that must run before tests.

Simulates a real code-generation build (OpenAPI client, protobuf, etc.) that a
repo expects you to run once after checkout. Stdlib only; no network.
"""

CLIENT_SOURCE = '''\
# AUTO-GENERATED by codegen.py — do not edit.

TAX_RATE = 0.23


def net_to_gross(net):
    """Convert a net amount to gross using the configured tax rate."""
    return round(net * (1 + TAX_RATE), 2)
'''


def main():
    with open("generated_client.py", "w") as f:
        f.write(CLIENT_SOURCE)
    print("generated_client.py written")


if __name__ == "__main__":
    main()
