"""Setup step 2/2: reads config.json and writes generated_client.py.

Fails if config.json is missing — gen_config.py (step 1) must run first.
Stdlib only; no network.
"""

import json
import os
import sys

TEMPLATE = '''\
# AUTO-GENERATED by codegen.py — do not edit.

TAX_RATE = {rate}


def net_to_gross(net):
    """Convert a net amount to gross using the configured tax rate."""
    return round(net * (1 + TAX_RATE), 2)
'''


def main():
    if not os.path.exists("config.json"):
        sys.exit("error: config.json not found — run `python3 gen_config.py` first")
    with open("config.json") as f:
        cfg = json.load(f)
    with open("generated_client.py", "w") as f:
        f.write(TEMPLATE.format(rate=cfg["tax_rate"]))
    print("generated_client.py written")


if __name__ == "__main__":
    main()
